[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
  "python3 -m ensurepip --upgrade",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install fastapi uvicorn[standard] python-multipart pillow numpy requests scikit-image scikit-learn",
  "python3 -m pip install umap-learn hdbscan"
]

[start]
cmd = "python -m uvicorn api.server:app --host 0.0.0.0 --port $PORT"
